// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ReClaim.Api;

#nullable disable

namespace ReClaim.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260220183014_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ReClaim.Api.Entities.Logistics", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssignedRecyclerId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_recycler_id");

                    b.Property<Point>("GeoSpatial")
                        .IsRequired()
                        .HasColumnType("geometry (point)")
                        .HasColumnName("geo_spatial");

                    b.Property<int>("ShardKey")
                        .HasColumnType("integer")
                        .HasColumnName("shard_key");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("tbl_logistics");
                });
#pragma warning restore 612, 618
        }
    }
}
