// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ReClaim.Api;

#nullable disable

namespace ReClaim.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260224163524_AddRecyclingRequestTables")]
    partial class AddRecyclingRequestTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ReClaim.Api.Domain.Entities.RecyclingRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AddressDetails")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("address_details");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Point>("PickupLocation")
                        .IsRequired()
                        .HasColumnType("geometry(Point, 4326)")
                        .HasColumnName("pickup_location");

                    b.Property<string>("RecyclerId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("recycler_id");

                    b.Property<string>("SellerId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("seller_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("tbl_recycling_requests");
                });

            modelBuilder.Entity("ReClaim.Api.Domain.Entities.RequestItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("EstimatedWeightKg")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("estimated_weight_kg");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("photo_url");

                    b.Property<decimal>("PredictedValue")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("predicted_value");

                    b.Property<Guid>("RecyclingRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("recycling_request_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("RecyclingRequestId");

                    b.ToTable("tbl_request_items");
                });

            modelBuilder.Entity("ReClaim.Api.Entities.Logistics", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssignedRecyclerId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_recycler_id");

                    b.Property<Point>("GeoSpatial")
                        .IsRequired()
                        .HasColumnType("geometry (point)")
                        .HasColumnName("geo_spatial");

                    b.Property<int>("ShardKey")
                        .HasColumnType("integer")
                        .HasColumnName("shard_key");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("tbl_logistics");
                });

            modelBuilder.Entity("ReClaim.Api.Domain.Entities.RequestItem", b =>
                {
                    b.HasOne("ReClaim.Api.Domain.Entities.RecyclingRequest", "RecyclingRequest")
                        .WithMany("Items")
                        .HasForeignKey("RecyclingRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecyclingRequest");
                });

            modelBuilder.Entity("ReClaim.Api.Domain.Entities.RecyclingRequest", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
